name: publish
on:
  release:
    types: [prereleased, released]
  workflow_dispatch:
    inputs:
      configuration:
        type: choice
        description: Configuration
        options: 
        - Release
        - Debug
      sha:
        description: 'Optional commit to deploy (latest if empty)'
      version:
        description: 'SemVer version to use (0.1.0-preview.[build] if empty)'

env:
  DOTNET_NOLOGO: true
  Configuration: Release
  PackOnBuild: true
  GeneratePackageOnBuild: true
  VersionLabel: ${{ github.ref }}
  VersionOrTag: ${{ github.event.inputs.version || github.event.release.tag_name || format('0.1.0-preview.{0}', github.run_number) }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  MSBUILDTERMINALLOGGER: auto
  SLEET_FEED_URL: https://api.nuget.org/v3/index.json

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ${{ vars.PUBLISH_AGENT || 'ubuntu-latest' }}
    steps:
      - name: 🔓 login
        uses: NuGet/login@v1
        id: login
        with:
          user: lparezanin
