name: Push NuGet package

on:
  push:
    branches: [main]

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: NuGet Login
      uses: NuGet/login@v1
      id: loginn
      with:
        user: lparezanin



    - name: Push package
      run: |
        dotnet nuget push ./src/*.nupkg \
          --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
          --source https://dev.nugettest.org/api/v2/package
          
