name: Push NuGet package


on:
  push:
    branches: [main]

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: NuGet Login
      uses: NuGet/login@v1
      id: loginn
      with:
        user: lparezanin
        token-service-url: https://dev.nugettest.org/api/v2/token
        audience: https://dev.nugettest.org



    - name: Push package
      run:  dotnet nuget push ./src/*.nupkg --api-key "${{steps.login.outputs.NUGET_API_KEY}}" --source https://dev.nugettest.org/v2/package

          
